### ISSUE TITLE
Dataset with text

### ISSUE THREAD

**Issue by mengqing0312** [lijiaman/omomo_release#1]
Hello, thank you for opening up such excellent work. It seems that there is no text description in the dataset released by OMOMO. When will the FullBodyManipulation dataset with text and its corresponding CHOIS work be open source. Thank you for your reply

**Comment by lijiaman** [comment]
Hi, I uploaded the text data here https://github.com/lijiaman/omomo_release/blob/main/omomo_text_anno.zip. As for CHOIS, the expected date for the release is in March.

**Comment by mengqing0312** [comment]
thanks for your reply!!
