### ISSUE TITLE
ModuleNotFoundError for human_body_prior.body_model

### ISSUE THREAD

**Issue by helloqxwang** [lijiaman/omomo_release#10]
I get error: `ModuleNotFoundError: No module named 'human_body_prior.body_model' ` when conducting `sh scriprts/test_omomo.sh after env set up`. 
After some checks, I find that this’s because the structure of human_body_prior packages have been changed. 
It can be solved simply by replacing `git clone https://github.com/nghorbani/human_body_prior.git` with `git clone -b old_master https://github.com/nghorbani/human_body_prior.git` in the README env setup part.

**Comment by OwenCaleb** [comment]
Yeah,you are absolutely right!You should not  git clone human_body_prior in the project.
because  'import human_body_prior' in .py in the project will wrongly locate the  human_body_prior package!
The truly package is  human_body_prior/src/human_body_prior!!!
