### ISSUE TITLE
visualisation image with a higher resolution

### ISSUE THREAD

**Issue by Dean-UQ** [lijiaman/omomo_release#11]
Hi Jiaman,

   Thanks for sharing the codes. Since some visualization images are not clear enough, which hyper-parameters in the visualization file should be reset for higher image resolution?

   Thx

**Comment by lijiaman** [comment]
If you're talking about the visualization for the rendered images, you can modify the .blend file manually (changing the resolution in Blender). https://github.com/lijiaman/omomo_release/blob/main/manip/vis/floor_colorful_mat.blend
