### ISSUE TITLE
About training/testing data split

### ISSUE THREAD

**Issue by Xiyan-Xu** [lijiaman/omomo_release#12]
Thanks for the great work!

In the paper, there are two training/test settings: use 15 objects for both training and testing, or 10 for training and 5 for testing.
For the previous one, I wonder if the training and testing datasets are exactly the same. I've checked code and didn't see the difference between the training and testing data in code level.

**Comment by lijiaman** [comment]
For these two training/testing split settings, subject 1-15 are used for training, subject 16, subject 17 are used for testing.
