### ISSUE TITLE
关于wandb.int()报错

### ISSUE THREAD

**Issue by 3DWen** [lijiaman/omomo_release#13]
I ran into this problem:
wandb.errors.errors.CommError: failed to upsert bucket: returned error 400 Bad Request: {"errors":[{"message":"you may not log runs directly to your organization, please try using your team entity","path":["upsertBucket"]}],"data":{"upsertBucket":null}}

**Comment by lijiaman** [comment]
Please check wandb related settings. You need to use your own wandb account.
