### ISSUE TITLE
Question about BPS representation of objects

### ISSUE THREAD

**Issue by Steve-Tod** [lijiaman/omomo_release#2]
Hi,

Thanks for making this great work public. I'm checking the BPS representation of the objects and have a few questions.

It seems you use BPS to represent the whole trajectory of the object, encoding the absolute position of vertices. However, the BPS uses a fixed data grid for representation (a sphere with radius of 1). Is this done by using the `custom_basis` argument of `bps_torch.encode`? Does the argument offer the encoding in the object-centric coordinate space?

Thank you!

**Comment by lijiaman** [comment]
Hi, 
When we compute the BPS representation, we always put the fixed sphere at the center of each object geometry. The object position information is provided separately. BPS does not contain information about the absolute position of the object. Please take a look at https://github.com/lijiaman/omomo_release/blob/main/manip/data/hand_foot_dataset.py#L335
