### ISSUE TITLE
Question about testing time

### ISSUE THREAD

**Issue by DonlynLee** [lijiaman/omomo_release#3]
Hello, thanks for your excellent work. I run the testing stage using the pretrained models you offered (It has been running for about three hours now), I wonder how much time does the testing stage take? The feedback I received is that Contact precision, TP + FP == 0!!, which means prediction no contact.

**Comment by lijiaman** [comment]
Please modify this line and reduce the sampling times accordingly to make evaluation faster https://github.com/lijiaman/omomo_release/blob/main/trainer_hand_foot_manip_diffusion.py#L569. Some sequences do not have contact in the ground truth sequences, that's why there exists TP+FP == 0.
