### ISSUE TITLE
Generate visualization

### ISSUE THREAD

**Issue by DonlynLee** [lijiaman/omomo_release#6]
Hi, sorry to bother you. I want to know if there is any other way to generate visualization (if running code on the server)?

**Comment by 3DWen** [comment]
> Hi, sorry to bother you. I want to know if there is any other way to generate visualization (if running code on the server)?
Have you found a way? I had the same problem.

**Comment by lijiaman** [comment]
The current blender visualization can be run on the server. Or you can use matplotlib to plot 3D joint positions instead.

**Comment by 3DWen** [comment]
> The current blender visualization can be run on the server. Or you can use matplotlib to plot 3D joint positions instead.
Do I need administrator rights to use blender?

**Comment by DonlynLee** [comment]
@3DWen hello, have you tried it?
