### ISSUE TITLE
About 'obj_com_pos' usage? 

### ISSUE THREAD

**Issue by jiajunzhang16** [lijiaman/omomo_release#8]
Hi jiaman, 

Thank you for your excellent work. 

I have a question regarding the dataset preprocessing code,  about the variable 'obj_com_pos' mentioned in hand_foot_dataset.py L423.   Although  it seems that 'obj_com_pos' isn't used in the final training process, where com_pos, encoding the object's center using the mean vertices of object geometry, I wonder what is ‘obj_com_pos’ in L423 refer to?
Besides, i'm curious about the impact of various preprocessing steps, such as 'face front', start at xy=0. Do these preprocessing influence the performance?

**Comment by lijiaman** [comment]
obj_com_pos should be the same as the object's center using the mean vertices of object geometry in our implementation. There could be some redundant data representation in the current data loader. 

As for the preprocessing steps, it's important to do this canonicalization (make the character "face front", start at xy=0). This is easier to learn compared to using the data without any preprocessing.
