### ISSUE TITLE
 Inquiry about BPS Data Representation and Normalization

### ISSUE THREAD

**Issue by mccuba** [lijiaman/omomo_release#9]
Hello,
I'm curious about the representation of the BPS (before being introduced to the diffusion model) in the format [x, y, z, x, y, z, ...] of size 1024*3. Specifically, I'd like to know if these values are normalized using z-score, min-max, or another method. Additionally, I'm wondering how missing values, such as 'nan' or 'none', from the BPS deltas are handled due to potential mismatches in some BPS points. 

thanks

**Comment by lijiaman** [comment]
We didn't do normalization for BPS representation. In our model, we use an MLP to project 1024*3 to a low-dimensional vector (512 or 256). There were no missing values in BPS. For each sampled point in the sphere, we found the nearest neighbor point on the object mesh and computed the distance vector.
